### ISSUE TITLE
Dynamax move

### ISSUE THREAD

**Issue by Hunaoa0519** [zThana/RemoRaids#14]
Dynamax move，seckill boss

**Comment by zThana** [comment]
Sorry, what?

**Comment by Hunaoa0519** [comment]
Great skill can kill boss in seconds

**Comment by Hunaoa0519** [comment]
sorry,I am a Baidu translator used by Chinese people

**Comment by Hunaoa0519** [comment]
Can it be prohibited Dynamax Or forbid a pokemon
I don't think it's in the configuration file

**Comment by zThana** [comment]
You can ban dynamax by adding `--dynamax=false` as argument when spawning the boss.

**Comment by Hunaoa0519** [comment]
Thank you. I succeeded in trying

**Comment by zThana** [comment]
Awesome! I'll close this then.
