### ISSUE TITLE
Boss won't spawn unless chunk is loaded.

### ISSUE THREAD

**Issue by chandlerthegreat** [zThana/RemoRaids#5]
I noticed that when players aren't around and the chunk is not loaded.. the bosses do not spawn... Landon referred me here to submit an issue and hope someone gets back to me.

**Comment by zThana** [comment]
Fully missed out on this one. Is this still an issue?

**Comment by chandlerthegreat** [comment]
Little late 😂. Server is dead unfortunately. Accidentally deleted it after
weeks maybe months of work

**Comment by zThana** [comment]
Sorry to hear, that does sound unfortunate. I'll close the issue then
